import Alignment from './fields/Alignment'
import Border from './fields/Border'
import BoxShadow from './fields/BoxShadow'
import Color from './fields/Color'
import Color2 from './fields/Color2'
import Divider from './fields/Divider'
import Dimension from './fields/Dimension'
import Gradient from './fields/Gradient'
import Layout from './fields/Layout'
import Link from './fields/Link'
import LinkButton from './fields/LinkButton'
import Media from './fields/Media'
import RadioImage from './fields/RadioImage'
import Range from './fields/Range'
import Select from './fields/Select'
import Tag from './fields/Tag'
import Toggle from './fields/Toggle'
import Typography from './fields/Typography'
import Separator from './fields/Separator'
import Template from './fields/Template'
import {Sections, Section} from './Sections'
import {CssGenerator} from './CssGenerator'
import {FieldGenerator} from './FieldGenerator'

wp.ultp = { Alignment, Border, BoxShadow, Color, Color2, Divider, Dimension, Gradient, Layout, Link, Media, RadioImage, Range, Select, Tag, Toggle, Typography, Separator, Template, Sections, Section, LinkButton, CssGenerator, FieldGenerator }